# Generated by Django 3.0.4 on 2020-03-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='master',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='slaves',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='slaves_all',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
