# Generated by Django 3.0.4 on 2020-03-29 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200328_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['rname']},
        ),
        migrations.AlterField(
            model_name='record',
            name='zone',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='config.Zone', verbose_name='Zone'),
        ),
    ]
