# Generated by Django 3.0.4 on 2020-03-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200329_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deleted'), ('N', 'New')], default='N', max_length=1, verbose_name='Status of this record'),
        ),
    ]
