# Generated by Django 3.0.4 on 2020-03-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='last_sync',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Time of the last sync with bind'),
        ),
    ]
