# Generated by Django 3.0.4 on 2020-04-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_zone_last_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='last_sync',
        ),
    ]
