# Generated by Django 3.0.4 on 2020-04-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_delete_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='enabled',
        ),
    ]
