# Generated by Django 3.0.4 on 2020-04-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_zone_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='admins',
        ),
    ]
