# Generated by Django 3.0.4 on 2020-04-08 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0010_remove_zone_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='owners',
        ),
        migrations.AddField(
            model_name='zone',
            name='owner',
            field=models.ForeignKey(default=1, help_text='User that owns this object. Staff users can modify all objects.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
