# Generated by Django 3.0.4 on 2020-04-09 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0012_auto_20200408_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='owner',
        ),
        migrations.AddField(
            model_name='zone',
            name='owners',
            field=models.ManyToManyField(help_text='Users that are allowed to modify this object. Staff users can modify all objects.', related_name='_zone_owners_+', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
    ]
