# Generated by Django 3.0.4 on 2020-04-07 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0008_remove_zone_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='DynDNS for this zone is enabled.')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_dyndns', to='config.Zone', verbose_name='Zone configuration')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hostname', max_length=255)),
                ('token', models.CharField(help_text='Authorization token for updating this host', max_length=255)),
                ('last_update', models.DateTimeField(blank=True, editable=False, help_text='Last successful update.', null=True, verbose_name='Last update')),
                ('admins', models.ManyToManyField(help_text='Local users that may modify this host.', to=settings.AUTH_USER_MODEL, verbose_name='Admin users')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_dyndns_hosts', to='dyndns.Zone', verbose_name='Zone')),
            ],
        ),
    ]
