# Generated by Django 3.0.4 on 2020-04-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyndns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='admins',
        ),
        migrations.AddField(
            model_name='host',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User that owns this object. Staff users can modify all objects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='zone',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User that owns this object. Staff users can modify all objects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='host',
            name='token',
            field=models.CharField(default='yDU1RafnEM5ZsZOetsKBdo0xZ0V6rZ7c', help_text='Authorization token for updating this host', max_length=255),
        ),
        migrations.AlterField(
            model_name='host',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='dyndns.Zone', verbose_name='Zone'),
        ),
    ]
