# Generated by Django 3.0.4 on 2020-04-09 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20200409_0607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyndns', '0002_auto_20200408_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hostname', max_length=255)),
                ('token', models.CharField(default='RPB6AeTgzWGG3L5SNkeeyiCOZIUXAmrf', help_text='Authorization token for updating this host', max_length=255)),
                ('last_update', models.DateTimeField(blank=True, editable=False, help_text='Last successful update.', null=True, verbose_name='Last update')),
                ('owners', models.ManyToManyField(help_text='Users that are allowed to modify this object. Staff users can modify all objects.', related_name='_dynhost_owners_+', to=settings.AUTH_USER_MODEL, verbose_name='Owners')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DynZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='DynDNS for this zone is enabled.')),
                ('owners', models.ManyToManyField(help_text='Users that are allowed to modify this object. Staff users can modify all objects.', related_name='_dynzone_owners_+', to=settings.AUTH_USER_MODEL, verbose_name='Owners')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_dyndns', to='config.Zone', verbose_name='Zone configuration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='zone',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.AddField(
            model_name='dynhost',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='dyndns.DynZone', verbose_name='Zone'),
        ),
    ]
