# Generated by Django 3.0.4 on 2020-04-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyndns', '0003_auto_20200409_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynhost',
            name='token',
            field=models.CharField(default='492CbRETuv8smZUwLkSQ6LdUtXPuCPqP', help_text='Authorization token for updating this host', max_length=255),
        ),
    ]
