# Generated by Django 3.0.4 on 2020-04-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyndns', '0004_auto_20200409_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynhost',
            name='token',
            field=models.CharField(default='5S50T5Tpl2MdEPemzYel7KHUiwDLRf2l', help_text='Authorization token for updating this host', max_length=255),
        ),
    ]
