# Generated by Django 3.0.4 on 2020-03-28 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this server. Maybe the FQDN?', max_length=255, unique=True)),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4 address')),
                ('ipv6', models.GenericIPAddressField(protocol='IPv6', verbose_name='IPv6 address')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('last_poll', models.DateTimeField(blank=True, null=True, verbose_name='Last polled')),
                ('admins', models.ManyToManyField(help_text='Users that may modify this server.', to=settings.AUTH_USER_MODEL, verbose_name='Admin users')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slaves_all', models.BooleanField(default=True, verbose_name='All servers are slaves')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_master', to='federation.Server', verbose_name='Master server')),
                ('slaves', models.ManyToManyField(blank=True, related_name='zones_slave', to='federation.Server', verbose_name='Slave servers')),
            ],
        ),
    ]
