# Generated by Django 3.0.4 on 2020-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Zone is enabled'),
        ),
    ]
