# Generated by Django 3.0.4 on 2020-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_server_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='enabled',
        ),
        migrations.AddField(
            model_name='zone',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Zone is enabled'),
        ),
    ]
