# Generated by Django 3.0.4 on 2020-03-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0004_server_nameserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this server. Maybe the FQDN?', max_length=255, unique=True)),
                ('url', models.URLField(help_text='URL where to pull the information.')),
                ('importer', models.CharField(choices=[('DE', 'Default')], default='DE', max_length=2, verbose_name='Importer')),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='remote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='federation.Remote', verbose_name='Remote configuration server'),
        ),
    ]
