# Generated by Django 3.0.4 on 2020-03-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0005_auto_20200329_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Remote is enabled'),
        ),
    ]
