# Generated by Django 3.0.4 on 2020-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0006_remote_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='remote',
        ),
        migrations.AddField(
            model_name='server',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Zone is enabled'),
        ),
        migrations.AddField(
            model_name='server',
            name='last_push',
            field=models.DateTimeField(blank=True, help_text='Last push to this server', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='last_received',
            field=models.DateTimeField(blank=True, help_text='Last push from this server', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='push_enabled',
            field=models.BooleanField(default=True, verbose_name='Zone is enabled'),
        ),
        migrations.AddField(
            model_name='server',
            name='push_url',
            field=models.URLField(default='', help_text='URL where to push the information.'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Remote',
        ),
    ]
