# Generated by Django 3.0.4 on 2020-03-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0007_auto_20200329_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='token',
            new_name='push_token',
        ),
        migrations.RemoveField(
            model_name='server',
            name='last_poll',
        ),
        migrations.AddField(
            model_name='server',
            name='receive_token',
            field=models.CharField(default='', max_length=255, verbose_name='Token'),
            preserve_default=False,
        ),
    ]
