# Generated by Django 3.0.4 on 2020-03-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0008_auto_20200329_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='receive_allow_others',
            field=models.BooleanField(default=False, verbose_name='Allow server to push zones for other servers as well'),
        ),
    ]
