# Generated by Django 3.0.4 on 2020-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0009_server_receive_allow_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='push_token',
            new_name='pull_token',
        ),
        migrations.RemoveField(
            model_name='server',
            name='last_push',
        ),
        migrations.RemoveField(
            model_name='server',
            name='push_enabled',
        ),
        migrations.RemoveField(
            model_name='server',
            name='push_url',
        ),
        migrations.RemoveField(
            model_name='server',
            name='receive_allow_others',
        ),
        migrations.RemoveField(
            model_name='server',
            name='receive_token',
        ),
        migrations.AddField(
            model_name='server',
            name='pull_enabled',
            field=models.BooleanField(default=True, verbose_name='Pull is enabled'),
        ),
        migrations.AddField(
            model_name='server',
            name='pull_last',
            field=models.DateTimeField(blank=True, help_text='Last pull from this server', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='pull_other_servers',
            field=models.ManyToManyField(related_name='_server_pull_other_servers_+', to='federation.Server', verbose_name='other servers to pull from here'),
        ),
        migrations.AddField(
            model_name='server',
            name='pull_url',
            field=models.URLField(default='', help_text='URL where to pull the information.'),
            preserve_default=False,
        ),
    ]
