# Generated by Django 3.0.4 on 2020-03-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0010_auto_20200329_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='last_received',
        ),
    ]
