# Generated by Django 3.0.4 on 2020-03-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0011_remove_server_last_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='pull_other_servers',
        ),
        migrations.AddField(
            model_name='server',
            name='pull_servers',
            field=models.ManyToManyField(related_name='_server_pull_servers_+', to='federation.Server', verbose_name='servers to pull from here'),
        ),
    ]
