# Generated by Django 3.0.4 on 2020-03-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0012_auto_20200329_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='pull_servers',
            field=models.ManyToManyField(blank=True, related_name='_server_pull_servers_+', to='federation.Server', verbose_name='servers to pull from here'),
        ),
        migrations.AlterField(
            model_name='server',
            name='pull_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='server',
            name='pull_url',
            field=models.URLField(blank=True, help_text='URL where to pull the information.'),
        ),
    ]
