# Generated by Django 3.0.4 on 2020-03-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0013_auto_20200329_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='auth_token',
            field=models.CharField(default='', max_length=255, verbose_name='Authorization token'),
        ),
    ]
