# Generated by Django 3.0.4 on 2020-04-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0016_auto_20200402_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='pull_servers',
            field=models.ManyToManyField(blank=True, related_name='servers', to='federation.Server', verbose_name='servers to pull from here'),
        ),
    ]
