# Generated by Django 3.0.4 on 2020-04-03 15:18

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0018_auto_20200403_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('remote'), nulls_last=False), 'name']},
        ),
        migrations.RemoveField(
            model_name='remote',
            name='pull_enabled',
        ),
    ]
