# Generated by Django 3.0.4 on 2020-04-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('federation', '0020_auto_20200403_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remote',
            name='admins',
        ),
        migrations.AddField(
            model_name='remote',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User that owns this object. Staff users can modify all objects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
