# Generated by Django 3.0.4 on 2020-04-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0022_auto_20200409_0607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zone',
            new_name='FedZone',
        ),
    ]
