# Generated by Django 3.0.4 on 2020-04-09 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('federation', '0023_auto_20200409_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedzone',
            name='owners',
            field=models.ManyToManyField(help_text='Users that are allowed to modify this object. Staff users can modify all objects.', related_name='_fedzone_owners_+', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
        migrations.AddField(
            model_name='server',
            name='owners',
            field=models.ManyToManyField(help_text='Users that are allowed to modify this object. Staff users can modify all objects.', related_name='_server_owners_+', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
    ]
